version: '2'

services:
  gitserver:
     image: jkarlos/git-server-docker:latest
     ports:
        - "2222:22"
     volumes:
        - ~/git-server/keys:/git-server/keys
        - ~/git-server/repos:/git-server/repos
  sonarqube:
     image: sonarqube:latest
     expose:
        - "9000"
        - "9092"
     ports:
        - "9000:9000"
        - "9092:9092"
  jenkins:
     image: dijkrosoft/jenkins:2.0
     expose:
        - "5000"
        - "8080"
     ports:
        - "8081:8080"
     depends_on:
       - sonarqube
