version: '2'

services:
  sonarqube:
     image: sonarqube:latest
     expose:
        - "9000"
        - "9092"
     ports:
        - "9000:9000"
        - "9092:9092"
  jenkins:
     image: jenkins/jenkins:lts
     expose:
        - "5000"
        - "8080"
     ports:
        - "8081:8080"
     depends_on:
       - sonarqube
