version: '3.1'

services:
  sonarqube:
     image: sonarqube:latest
     expose:
        - "9000"
        - "9092"
     ports:
        - "9000:9000"
        - "9092:9092"
     container_name: sq

  jenkins:
     image: jenkins/jenkins:lts
     expose:
        - "5000"
        - "8080"
     ports:
        - "8081:8080"
     volumes:
        - ~/_LOCAL_GIT_SHARE:/mnt
     depends_on:
       - sonarqube
     container_name: jenk
