version: '2'

services:
  sonarqube:
     image: dijkrosoft/sonarqube:1.0
     expose:
        - "9000"
        - "9092"
     ports:
        - "9000:9000"
        - "9092:9092"
  jenkins:
     image: dijkrosoft/jenkins:1.0
     expose:
        - "5000"
        - "8080"
     ports:
        - "8081:8080"
     volumes:
        - ~/_LOCAL_GIT_SHARE:/mnt
     depends_on:
       - sonarqube
